### ISSUE TITLE
Question：what is the package cyclomatic complexity

### ISSUE THREAD

**Issue by seekelvis** [bkielbasa/cyclop#14]
Cyclop is a great tool to help us calculate the complexity. But I can't understand the parameter `package-average`. What's the different between it and function cyclomatic complexity. Does anybody know?

**Comment by bkielbasa** [comment]
Hi! Thanks for your question!

The difference is that the `package-average` calculates the cyclomatic complexity for every function and takes the average of it. It means, that if you have 2 functions in the package with the complexity 5 and 10, the average will be 7,5.

**Comment by bkielbasa** [comment]
I'm closing the issue but if you have any questions - just reopen it and I'll be happy to answer more questions :)
