### ISSUE TITLE
"go get github.com/bkielbasa/cyclop/cmd/cyclop" but binary not in path after installation

### ISSUE THREAD

**Issue by huornlmj** [bkielbasa/cyclop#20]
When I run 

```console
$ go get github.com/bkielbasa/cyclop/cmd/cyclop
```
cyclop is installed.  But when I try to run it the cyclop executable is not in any path and I get `cyclop: command not found`.

**Comment by bkielbasa** [comment]
Hi @huornlmj, thanks for your input! Sorry for late response :(

It happens because your go bin path isn't in your `PATH`. You have to add it somewhere in your `bashrc` or `zshrc` file:

```
PATH=$PATH:`go env GOPATH`/bin
```

in case of any problems - let me know :)
