### ISSUE TITLE
Update  golang.org/x/tools to latest version

### ISSUE THREAD

**Issue by jackdelahunt** [bkielbasa/cyclop#21]
The current version of `golang.org/x/tools` used is `v0.9.3`. I am getting a few panic on larger codebases when using this tool. The panic was coming from loading the packages which is done inside `golang.org/x/tools`. Updating the package to the latest version `v0.26.0` fixed this issue.

**Comment by bkielbasa** [comment]
thanks @jackdelahunt for reporting the issue, I've just merged a fix for that. Hope it works for you now without panicking :)
